In [1]:
# Week-5: Pandas
# Week-6: numpy

In [3]:
# Numpy= library--> import this--> numerical python-->numpy
# Specially used for numerical functions on matrices. But only limited to this.

In [5]:
import numpy as np
# 1 dimensional array
A=[4,5,6,7]
print(A)
arr=np.array(A)
print(arr)

[4, 5, 6, 7]
[4 5 6 7]


In [7]:
# 2D list
A=[[1,2,3],[4,5,6]]
arr_2D = np.array(A)
print(arr_2D)
print(np.ndim(arr))
print(np.ndim(arr_2D))

[[1 2 3]
 [4 5 6]]
1
2


In [9]:
print(np.shape(arr))
print(np.shape(arr_2D))

(4,)
(2, 3)


In [11]:
print(np.size(arr))

4


In [13]:
# Similar to range function in for loop---> there's function
# called arrange() in np

In [19]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
A= np.arange(50)
A.resize(6,10) # Row,column
A.resize(6,10,2) #block,rows,column # This is an example of tensor
print(A)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]
  [30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]
  [ 0  0]]]


In [25]:
A=np.arange(50)
print(A.reshape(25,2))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]


In [27]:
print(A.reshape(-1,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [29]:
# Let's create a random numpy array of certain size
arr=np.random.randint(1,101)
print(arr)

92


In [31]:
arr=np.random.randint(1,101,size=10)
print(arr)

[61 96 74 72 71 21 34 91 22 82]


In [33]:
arr=np.random.randint(1,101,size=(3,6))
print(arr)

[[78 16 64 90 12 93]
 [18 41 39  4 59 21]
 [30 65 75 96 40 75]]


In [37]:
# Basic of a matrix operation
# Transposition
print("T",arr.T)

T [[78 18 30]
 [16 41 65]
 [64 39 75]
 [90  4 96]
 [12 59 40]
 [93 21 75]]


In [39]:
arr1=np.random.randint(1,101,size=(3,6))
arr2=np.random.randint(1,101,size=(3,6))
print(arr1)
print("\n",arr2)

[[48 23 60 12 51 33]
 [73 80 28 36 54 34]
 [42 66 58 35 80 33]]

 [[ 37  78  30  48  79  23]
 [ 40  35  57  13  35 100]
 [ 62  16  69  96  66 100]]


In [41]:
print(arr1+arr2)

[[ 85 101  90  60 130  56]
 [113 115  85  49  89 134]
 [104  82 127 131 146 133]]


In [43]:
print(arr1-arr2)

[[ 11 -55  30 -36 -28  10]
 [ 33  45 -29  23  19 -66]
 [-20  50 -11 -61  14 -67]]


In [45]:
print(arr1*arr2)

[[1776 1794 1800  576 4029  759]
 [2920 2800 1596  468 1890 3400]
 [2604 1056 4002 3360 5280 3300]]


In [47]:
print(arr1+2)

[[50 25 62 14 53 35]
 [75 82 30 38 56 36]
 [44 68 60 37 82 35]]


In [51]:
# Rules of matrix
# The number of row of first matrix is equal to number of column in second matrix
# 2*3=3*2

In [53]:
# print(np.matmul(arr1,arr2)): For matrix multiplication

In [63]:
# Linear algebra---> rank, inverse, determinant
# Linear algebra---> square matrix
arr1=np.random.randint(1,101,size=(4,4))
print(arr1)

[[ 1 40  5 71]
 [98 90 49 66]
 [ 8 13 61 31]
 [18 68 91 35]]


In [65]:
print(np.linalg.inv(arr1))

[[-0.00902484  0.01174902  0.00920566 -0.01200135]
 [ 0.00399116 -0.00130774 -0.02839197  0.01951686]
 [-0.00595988 -0.0016101   0.01366291  0.0030248 ]
 [ 0.01238279  0.00068466  0.01490364 -0.01103939]]


In [67]:
print(np.linalg.det(arr1))
print(np.linalg.matrix_rank(arr1))

19549717.00000002
4


In [69]:
# axis in numpy arrays. (Only for 2nd and more)
arr1=np.random.randint(1,101,size=(3,6))
print(arr1)

[[35 67 10 75 39 79]
 [36  7 13 54 98 94]
 [48 84 66  8 20 19]]


In [71]:
print(np.sort(arr1,axis=None))

[ 7  8 10 13 19 20 35 36 39 48 54 66 67 75 79 84 94 98]


In [73]:
print(np.sort(arr1))

[[10 35 39 67 75 79]
 [ 7 13 36 54 94 98]
 [ 8 19 20 48 66 84]]


In [75]:
print(np.sort(arr1,axis=0))

[[35  7 10  8 20 19]
 [36 67 13 54 39 79]
 [48 84 66 75 98 94]]


In [83]:
print(np.sort(arr1))

[[10 35 39 67 75 79]
 [ 7 13 36 54 94 98]
 [ 8 19 20 48 66 84]]


In [87]:
print(np.sum(arr1,axis=1))

[305 302 245]


In [93]:
print(np.mean(arr1,axis=0))

[39.66666667 52.66666667 29.66666667 45.66666667 52.33333333 64.        ]


In [95]:
print(np.argmax(arr1, axis=0)) #arg=index of maximum

[2 2 2 0 1 1]


In [97]:
# Create two random matrices having elements between 50 and 200 of size 4*4 each
# Perform matrix multiplication and element wise multiplication
# Perform addtional of two matrix.
# Add 10 to each element of both matrix
# Find determinant, rank and inverse of both matrices. Confirm the inverse by multiplication
# With original matrix @ A*inv(A)=I
# Practice mean(), sum(), max(), min(), std(), argmax() with axis 0,1 and none

In [123]:
# Create two random matrices having elements between 50 and 200 of size 4*4 each
a1=np.random.randint(50,200,size=(4,4))
a2=np.random.randint(50,200,size=(4,4))
print(a1)
print()
print(a2)
print()
print(np.matmul(a1,a2))
print()
print(a1+a2)
print()
print(a1+10)
print(a2+10)
print()
print(np.linalg.det(a1))
print(np.linalg.det(a2))
print(np.linalg.inv(a1))
print(np.linalg.inv(a2))
print(np.linalg.matrix_rank(a1,a2))
print()
print(a1*np.linalg.inv(a1))==print(np.linalg.inv(a1))
print()
print(a2*np.linalg.inv(a1))==print(np.linalg.inv(a2))


[[124  58 127  93]
 [172 136  64 100]
 [102 173  98  82]
 [122 133 106 174]]

[[ 72  74  71  84]
 [150 168 186 153]
 [163  88  83  65]
 [ 95 104 185 123]]

[[47164 39768 47338 38984]
 [52716 51608 61320 51716]
 [57058 53764 62724 51493]
 [62542 58796 74388 58889]]

[[196 132 198 177]
 [322 304 250 253]
 [265 261 181 147]
 [217 237 291 297]]

[[134  68 137 103]
 [182 146  74 110]
 [112 183 108  92]
 [132 143 116 184]]
[[ 82  84  81  94]
 [160 178 196 163]
 [173  98  93  75]
 [105 114 195 133]]

141765791.99999973
21632796.000000004
[[ 0.00309536  0.01029684 -0.00519214 -0.00512527]
 [-0.00583994 -0.00037555  0.00857442 -0.00070364]
 [ 0.01054223 -0.0086758   0.00593461 -0.00344532]
 [-0.00412873 -0.00164731 -0.00652888  0.01197742]]
[[ 0.00504567 -0.01014682  0.01141018  0.00314606]
 [-0.02562526  0.03489489 -0.00822876 -0.02155713]
 [-0.01879812  0.00057043  0.00102594  0.01158602]
 [ 0.04604342 -0.02252561 -0.00339817  0.00650124]]
[[2 2 2 2]
 [1 1 1 1]
 [1 1 2 2]
 [1 1 1 1]]

[[ 0.38

True