In [1]:
# numpy split ans stack -vstack and hstack- hsplit and vsplit
import numpy as np
arr =np.random.randint(1,10,size=(4,6))
print(arr,"\n")

# split
print("hsplit\n",np.hsplit(arr,2))
print("vsplit\n",np.vsplit(arr,2))

[[1 3 5 2 1 1]
 [5 1 8 3 7 3]
 [7 1 7 2 5 8]
 [3 5 6 9 3 7]] 

hsplit
 [array([[1, 3, 5],
       [5, 1, 8],
       [7, 1, 7],
       [3, 5, 6]]), array([[2, 1, 1],
       [3, 7, 3],
       [2, 5, 8],
       [9, 3, 7]])]
vsplit
 [array([[1, 3, 5, 2, 1, 1],
       [5, 1, 8, 3, 7, 3]]), array([[7, 1, 7, 2, 5, 8],
       [3, 5, 6, 9, 3, 7]])]


In [3]:
print("hsplit\n",np.hsplit(arr,[2]))

hsplit
 [array([[1, 3],
       [5, 1],
       [7, 1],
       [3, 5]]), array([[5, 2, 1, 1],
       [8, 3, 7, 3],
       [7, 2, 5, 8],
       [6, 9, 3, 7]])]


In [7]:
arr1=np.array([[2,3],[5,6]]) # horizontal direction it stack the array
# hstack 
print("hstack\n",np.hstack(arr1))

hstack
 [2 3 5 6]


In [9]:
arr1=np.array([[2,3],[5,6]]) # In vertical direction it stack the element.
# vstack 
print("vstack\n",np.vstack(arr1))

vstack
 [[2 3]
 [5 6]]


In [27]:
a1=np.array([[2,3,4],[5,6,7]])
a2=np.array([[1],[3]])
a3=np.hstack((a1,a2))
print(a3)

[[2 3 4 1]
 [5 6 7 3]]
